### ISSUE TITLE
复疾勘误

### ISSUE THREAD

**Issue by Sine-Enis** [DeltaGreenCHN/Control-Group#1]
你好！复疾模组的v1.0.3译文一如既往地出色，但是初读下来发现有在医学名词的文本上存在歧义（如p21页码19的M2离子通道抑制剂，此类药物为M2蛋白抑制剂，通过阻止病毒脱壳实现抗病毒作用），由于我手头没有原文（再次感谢翻译大佬的付出），不能确定这属于原文的错误还是误译，因此我有意对该篇译文作一个完整的校对（相关专业在读），联系方式是2232866379@qq.com，打扰致歉！:p

**Comment by dkwingsmt** [comment]
已私信联系，非常感谢！
